CREATE TABLE USER (
	USER_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	`PASSWORD` VARCHAR(30) NOT NULL,
	STATUS ENUM('Dormant','Active','Inactive','Deleted'),
	CREATED_BY TINYINT UNSIGNED,
	CREATED_ON TIMESTAMP,
	MODIFIED_BY TINYINT UNSIGNED,
	MODIFIED_ON TIMESTAMP,
	PRIMARY KEY(USER_ID)
);

CREATE TABLE EXP_PAYMENT_MODE (
	EXP_PAYMENT_MODE_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	USER_ID TINYINT DEFAULT NULL,
	STATUS ENUM('Active','Inactive','Deleted'),
	CREATED_BY TINYINT UNSIGNED,
	CREATED_ON TIMESTAMP,
	MODIFIED_BY TINYINT UNSIGNED,
	MODIFIED_ON TIMESTAMP,
	PRIMARY KEY(EXP_PAYMENT_MODE_ID)
);

ALTER TABLE EXP_PAYMENT_MODE MODIFY USER_ID TINYINT UNSIGNED;

ALTER TABLE EXP_PAYMENT_MODE DROP FOREIGN KEY PMNT_MODE_USER_ID;

ALTER TABLE EXP_PAYMENT_MODE ADD CONSTRAINT
FK_PMNT_MODE_USER_ID 
FOREIGN KEY(USER_ID) 
REFERENCES TracExp.`USER`(USER_ID);

CREATE TABLE EXP_CATEGORY (
	EXP_CATEGORY_ID TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	USER_ID TINYINT DEFAULT NULL,
	STATUS ENUM('Active','Inactive','Deleted'),
	CREATED_BY TINYINT UNSIGNED,
	CREATED_ON TIMESTAMP,
	MODIFIED_BY TINYINT UNSIGNED,
	MODIFIED_ON TIMESTAMP,
	PRIMARY KEY(EXP_CATEGORY_ID)
);

ALTER TABLE EXP_CATEGORY ADD COLUMN TYPE ENUM('Expense','Income');
ALTER TABLE EXP_CATEGORY ADD COLUMN IS_RETURNABLE BIT(1) NOT NULL DEFAULT B'0';

ALTER TABLE EXP_CATEGORY MODIFY USER_ID TINYINT UNSIGNED;
ALTER TABLE EXP_CATEGORY MODIFY `TYPE` ENUM('Expense','Income','Savings');

ALTER TABLE EXP_CATEGORY DROP FOREIGN KEY CATEGORY_USER_ID;

ALTER TABLE EXP_CATEGORY ADD CONSTRAINT
FK_CATEGORY_USER_ID 
FOREIGN KEY(USER_ID) 
REFERENCES TracExp.`USER`(USER_ID);

CREATE TABLE EXP_TRANSACTION (
	EXP_TRANSACTION_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	TRANSACTION_DATE TIMESTAMP NOT NULL,
	CREDIT FLOAT(10,2) NOT NULL,
	DEBIT FLOAT(10,2) NOT NULL,
	EXP_PAYMENT_MODE_ID TINYINT UNSIGNED NOT NULL,
	EXP_CATEGORY_ID TINYINT UNSIGNED NOT NULL,
	PARENT_EXP_TRANSACTION_ID  SMALLINT UNSIGNED DEFAULT NULL,
	REMARKS VARCHAR(100),
	USER_ID TINYINT UNSIGNED NOT NULL,
	RETURN_DATE TIMESTAMP,
	STATUS ENUM('Active','Inactive','Deleted'),
	CREATED_BY TINYINT UNSIGNED,
	CREATED_ON TIMESTAMP,
	MODIFIED_BY TINYINT UNSIGNED,
	MODIFIED_ON TIMESTAMP,
	PRIMARY KEY(EXP_TRANSACTION_ID),
	CONSTRAINT FK_EXP_TXN_USER_ID FOREIGN KEY(USER_ID) REFERENCES `USER`(USER_ID),
	CONSTRAINT FK_EXP_TXN_TXN_ID FOREIGN KEY(PARENT_EXP_TRANSACTION_ID) REFERENCES `EXP_TRANSACTION`(EXP_TRANSACTION_ID),
	CONSTRAINT FK_EXP_PMT_MODE_ID FOREIGN KEY(EXP_PAYMENT_MODE_ID) REFERENCES `EXP_PAYMENT_MODE`(EXP_PAYMENT_MODE_ID),
	CONSTRAINT FK_EXP_CAT_ID FOREIGN KEY(EXP_CATEGORY_ID) REFERENCES `EXP_CATEGORY`(EXP_CATEGORY_ID)
); 

CREATE TABLE EXP_USER_ACC_BALANCE (
	EXP_USER_ACC_BALANCE_ID SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	OPENING_BALANCE FLOAT(10,2) NOT NULL,
	CLOSING_BALANCE FLOAT(10,2) NOT NULL,
	USER_ID TINYINT UNSIGNED NOT NULL,
	STATUS ENUM('Active','Inactive','Deleted'),
	CREATED_BY TINYINT UNSIGNED,
	CREATED_ON TIMESTAMP,
	MODIFIED_BY TINYINT UNSIGNED,
	MODIFIED_ON TIMESTAMP,
	PRIMARY KEY(EXP_USER_ACC_BALANCE_ID),
	CONSTRAINT FK_EXP_USER_ACC_USER_ID FOREIGN KEY(USER_ID) REFERENCES `USER`(USER_ID),
	CONSTRAINT UK_USER_NAME_STATUS UNIQUE (USER_ID,NAME,STATUS)
);



